---
- name: i3status directory structure
  when: ansible_system == "Linux"
  file:
    path: '{{ item }}'
    state: directory
    mode: 0700
  with_items:
    - '{{ home }}/.config/i3status'

- name: i3status configuration
  when: ansible_system == "Linux"
  template:
    src: '{{ item }}.j2'
    dest: '{{ home }}/.config/i3status/{{ item }}'
    mode: 0400
  with_items:
    - config
