---
- name: Tmux package
  package:
    name: tmux
    state: present
  become: '{{ use_become  }}'

- name: Tmux configuration
  template:
    src: tmux.conf.j2
    dest: '{{ home }}/.tmux.conf'
    mode: 0400
