---
- name: i3 package
  when: ansible_system == "Linux"
  package:
    name: i3-wm
    state: present
  become: '{{ use_become }}'

- name: i3 directory structure
  when: ansible_system == "Linux"
  file:
    path: '{{ item }}'
    state: directory
    mode: 0700
  with_items:
    - '{{ home }}/.config/i3'

- name: i3 configuration
  when: ansible_system == "Linux"
  template:
    src: '{{ item }}.j2'
    dest: '{{ home }}/.config/i3/{{ item }}'
    mode: 0400
  with_items:
    - config
