---
- name: Nat's Sensible Dot-file Setup
  hosts: all
  pre_tasks:
    - group_by: key={{ ansible_system | lower }}
  roles:
    - prerequisites
    - powerline
    - fish
    - tmux
    - termite
    - inputrc
    - htop
    - vis
    - bc
    - task
    - gitconfig
    - bin-scripts
    - fontconfig
    - x
    - i3
    - i3status
    - sway
